site_name: NewsBetter Documentation
repo_url: https://github.com/SnakesAndLadders/NewsBetter/
copyright: 2020 - Shawn Ayotte
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage: usage.md
  - About: about.md
theme: readthedocs
